fix: fix parsing foundation bank payment
thu-info-community/thu-info-app pull request #616
Opened 2024-10-10 16:57 UTC by SunnyCloudYang

**What is the purpose of this PR?**

- [x] Fixing a bug

**Is there a related issue?**

#615 

- [x] I understand that *adding a new feature* before *creating a feature request issue* has a high chance of rejection.

**Please describe your changes.**

Add a check to see if there's table after the selected title, it is a valid item if so and vise versa.

**Are there any possible drawbacks or side-effects?**

I have not fully tested it, so it may cause failure when parsing data.

**How to verify the changes?**

Compile the modified version and check if the item was properly rendered, but as I have some problems in configuring my RN so I can't verify it by myself...

2024-10-10 17:09 UTC, 84634E1A607A commented
感谢您的贡献~ 有点忙，可能得过两天再看 😘

2024-10-14 02:51 UTC, UNIDY2002 requested changes

2024-10-14 02:51 UTC, UNIDY2002 commented on apps/thu-info-app/src/ui/home/bankPayment.tsx
这个文件是有啥空白符改过了么，能尽量缩减一些更改么，谢谢 :)

2024-10-14 03:22 UTC, SunnyCloudYang commented on apps/thu-info-app/src/ui/home/bankPayment.tsx
不小心改成了crlf🥲

2024-10-14 07:31 UTC, 84634E1A607A commented on apps/thu-info-app/ios/Podfile.lock
这里面是啥

2024-10-14 07:44 UTC, SunnyCloudYang commented on apps/thu-info-app/ios/Podfile.lock
是merge了那个bot的commit导致的，应该是什么依赖库的版本升级？需要discard吗？

2024-10-14 07:47 UTC, 84634E1A607A commented
笑死, 又发现了个 Bug, 在切换到 代发 之后切换回 代发 (基金会), 会由于代发获取太慢导致代发的列表覆盖代发 (基金会) 的列表. 以上 Commit 用于修复此问题.

2024-10-14 07:47 UTC, UNIDY2002 commented on apps/thu-info-app/ios/Podfile.lock
这个没关系，不用改

2024-10-14 07:52 UTC, SunnyCloudYang commented
> 笑死, 又发现了个 Bug, 在切换到 代发 之后切换回 代发 (基金会), 会由于代发获取太慢导致代发的列表覆盖代发 (基金会) 的列表. 以上 Commit 用于修复此问题.
> 
> (代发加载太慢也是个大问题...)

大概是信息中心那边查询太慢了，考虑做个上滑加载更多？

2024-10-14 08:04 UTC, 84634E1A607A commented
刚刚看了一下, 由于很多同学的代发不是每个月都有, 不太好确定截止时间应该放在什么时候. 比如如果我的上一个代发是去年 12 月, 那么如果上划加载就会有相当长的时间啥也显示不出来. 不如摆烂 (x

2024-10-14 09:26 UTC, merged